### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by johndroid** [jonaird/upstate#2]
When I ran the upstate example, there was an unhandled exception at line 60 of base.dart.  I made a temporary fix by setting notifyParent to false on line 23.  This handles the case where parent is null in the constructor.

Or, you might consider an else case in the constructor.

**Comment by jonaird** [comment]
I'm not able to reproduce the error. The example code seems to work fine for me. If the parent it null it should not call notifyChange on its parent.

**Comment by johndroid** [comment]
When the FloatingActionButton is tapped, the increment function at line 83 of custom_state_object_example.dart is called.  That in turn calls notifyChange in base.dart.  Since notifyParent has not been properly initialized, it is null when line 60 is executed.  This generates an exception.
![Capture](https://user-images.githubusercontent.com/8131205/86298379-3a56b800-bbc3-11ea-9428-801d46a439c1.PNG)

**Comment by jonaird** [comment]
I set notifyParent to false for the CounterModel in the example which should fix the issue but I'm working on an overhaul of the API that should make things like this much clearer and easier to use.

**Comment by johndroid** [comment]
Setting notifyParent to false in custom_state_object_example.dart doesn't fix the problem.  It needs to be set in the base class, such as in the constructor.

**Comment by jonaird** [comment]
Thanks. Will release 1.0 soon where this type of bug will no longer be possible.
